<a href="https://colab.research.google.com/github/vk8teen/data_science_Q-A/blob/main/Numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
A = np.arange(2,14).reshape(3,-1)
B = np.arange(5,21).reshape(4,-1)
(rows, columns) = np.shape(A)
rows

3

Given two 2D arrays, row and column ranges,

Perform the following operations:

Find the matrix multiplication of the given two matrices and
Extract the elements from the output of above step using the given ranges
If matrix multiplication is not possible, return -1
Note: The end points (upper range) of both rows and columns are excluded.

In [ ]:
import numpy as np
def matrixmul(mat1, mat2, r1, r2, c1, c2):

  #unpacking number of rows and number of columns of each patrics
  r_m1, c_m1 = np.shape(mat1)
  r_m2, c_m2 = np.shape(mat2)

  #checking whether no. of column of first matrix is equal to number of rows of second martrix for possibility of matrix multiplication.
  # if it is not equal then return -1.
  if c_m1 != r_m2:
    result = -1
  else:
    mat3 = np.dot(mat1,mat2)

    # extracting specific rows and columns from the resultant matrix of matrix multiplication.

    result = (mat3[r1:r2, c1:c2])
  return result


A = np.array([[1,2],[2,3],[3,4]])
B = np.array([[1,2],[3,4],[10, 20]])

matrixmul(A,B, 1, 3, 1, 3)

-1

Given a list of birds and their corresponding age, return the name of birds sorted according to age (ascending).

Input Format:

Two 1D array list i.e. bird array and age array

In [ ]:
birds = np.array(['spoonbills',  'plovers',  'plovers',  'plovers',  'plovers',  'Cranes',  'plovers',  'plovers',  'Cranes',  'spoonbills'])
age = np.array([5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0])

import numpy as np
def bird_sort(bird, age):

  # Getting the sorted index of age.
  sorted_age_index = np.argsort(age)

  # Use the index from previous step to get sorted birds

  sorted_birds = birds[sorted_age_index]

  return sorted_birds

bird_sort(birds, age)

array(['plovers', 'plovers', 'plovers', 'plovers', 'plovers', 'Cranes',
       'spoonbills', 'Cranes', 'plovers', 'spoonbills'], dtype='<U10')

Given a list of birds and their corresponding age, calculate the mean age of the Crane bird (rounded off to 2 decimal points)

In [ ]:
import numpy as np

def calculate_mean_age(birds, age):

    mean_age = None

    ## STEP1. Create mask to get Crane birds from birds array
    mask = birds == "Cranes"

    ## STEP2. Get the age of crane birds

    crane_ages = age[mask]

    ## STEP 3. Calculate mean age of crane birds and rounf of to 2 decimal point

    mean_age = np.round(np.mean(crane_ages),2)

    return mean_age

birds = np.array(['spoonbills',  'plovers',  'plovers',  'plovers',  'plovers',  'Cranes',  'plovers',  'plovers',  'Cranes',  'spoonbills'])
age = np.array([5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0])


calculate_mean_age(birds, age)

4.75

Given a array of bird names and another array with corresponding ages of the birds, find the name of the oldest bird in the list.

In [ ]:
import numpy as np
def oldest_bird(birds, age):

    ## STEP 1: Get the index of maximum age element

    max_age_index = np.where(age == max(age))
    print(max_age_index)

    ## STEP 2: Get the bird with maxium age using the above index

    old_bird = birds[max_age_index]
    return old_bird

birds1 = np.array(['sparrow', 'peacock', 'parrot', 'owl', 'peacock', 'macaw', 'macaw', 'parrot', 'macaw', 'peacock'])
age1 = np.array([6, 1, 6, 5, 7, 6, 0, 9, 0, 7])
oldest_bird(birds1,age1)



(array([7]),)


array(['parrot'], dtype='<U7')

Given a NumPy array of shape (n,m). Add padding of a layer of 0’s on all 4 boundaries of the matrix.

In [ ]:
import numpy as np
def add_padding(mat):
    '''mat-> NumPy array
       output-> NumPy array is expected to be returned'''

    mat1 = np.vstack(([0]*mat.shape[1],mat,[0]*mat.shape[1]))
    B = np.array([0]*mat1.shape[0]).reshape(-1,1)
    mat2 = np.hstack((np.array([0]*mat1.shape[0]).reshape(-1,1),mat1,np.array([0]*mat1.shape[0]).reshape(-1,1)))
    print(mat2)

    res = mat2

    return res

In [ ]:
A = np.arange(12).reshape(3,-4)
add_padding(A)

[[ 0  0  0  0  0  0]
 [ 0  0  1  2  3  0]
 [ 0  4  5  6  7  0]
 [ 0  8  9 10 11  0]
 [ 0  0  0  0  0  0]]


array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  1,  2,  3,  0],
       [ 0,  4,  5,  6,  7,  0],
       [ 0,  8,  9, 10, 11,  0],
       [ 0,  0,  0,  0,  0,  0]])

Given an MxN 2D array (M >= 4),

Split the array column wise such that,

1st sub array contains the first 2 columns
2nd sub array contains the 3rd column
3rd sub array contains the rest of the columns

In [ ]:
import numpy as np

def split(arr):

    subarrays = np.split(arr,[2,3], axis = 1)
    print(arr)
    return subarrays

A = np.arange(21).reshape(3,-1)
split(A)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]


[array([[ 0,  1],
        [ 7,  8],
        [14, 15]]),
 array([[ 2],
        [ 9],
        [16]]),
 array([[ 3,  4,  5,  6],
        [10, 11, 12, 13],
        [17, 18, 19, 20]])]

Given an 1D array and an integer k that specifies the number of equal parts to split the array into,

Perform the following operations:

Split the array into k number of equal parts.
Return the list of split arrays.

In [ ]:
import numpy as np

def split(arr,k):

    subarrays = np.split(arr,3)
    print(arr)
    return subarrays

A = np.arange(21)
split(A, 3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


[array([0, 1, 2, 3, 4, 5, 6]),
 array([ 7,  8,  9, 10, 11, 12, 13]),
 array([14, 15, 16, 17, 18, 19, 20])]